AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: DTrainingManager application

Globals:
  Function:
    Architectures:
      - x86_64
    MemorySize: 128
    Runtime: !Ref PythonRuntimeVersion
    Timeout: 5
    Tracing: Active

Parameters:
  PythonRuntimeVersion:
    Type: String
    Default: python3.13
    Description: The Python runtime version to use for the Lambda function.
    AllowedValues:
      - python3.13
    ConstraintDescription: Must be a valid Python runtime version.
  SecretsManagerTelegramApiKeyName:
    Type: String
    Default: d-training-manager/telegram-api-key
    Description: The name of the secret form Secrets Manager containing the Telegram API key.
  Stage:
    Type: String
    Default: prod
    Description: The stage for the application (e.g., dev, prod)
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: Must be one of the allowed values.

Resources:
  DTrainingManagerHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      FailOnWarnings: true
      Name: !Sub "d-training-manager-${Stage}-http-api"
      StageName: !Ref Stage
  DTrainingManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "d-training-manager-${Stage}-lambda"
      Handler: d_training_manager.app.lambda_handler
      CodeUri: .
      Description: DTrainingManager API handler
      Layers:
        - !Ref DTrainingManagerFunctionLayer
      Events:
        ProxyPath:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            ApiId: !Ref DTrainingManagerHttpApi
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: d-training-manager
          POWERTOOLS_LOG_LEVEL: INFO
          POWERTOOLS_LOGGER_LOG_EVENT: true
          POWERTOOLS_METRICS_NAMESPACE: DTrainingManager
          TELEGRAM_API_TOKEN: !Ref SecretsManagerTelegramApiKeyName
          STAGE: !Ref Stage
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretsManagerTelegramApiKeyName}-*
      Tags:
        LambdaPowertools: python
    Metadata:
      BuildMethod: makefile
  DTrainingManagerFunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "d-training-manager-${Stage}-lambda-layer"
      Description: DTrainingManager Lambda Layer
      ContentUri: .
      CompatibleRuntimes:
        - python3.13
    Metadata:
      BuildMethod: makefile

Outputs:
  DTrainingManagerHttpApiUrl:
    Description: "API Gateway endpoint URL for Swagger page"
    Value: !Sub "https://${DTrainingManagerHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${Stage}/swagger"

  DTrainingManagerFunction:
    Description: "DTrainingManager Lambda Function ARN"
    Value: !GetAtt DTrainingManagerFunction.Arn
